name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-pnpm-combo:
          - node-version: 18.x
            pnpm-version: 10
          - node-version: 20.x
            pnpm-version: 10
          - node-version: 22.x
            pnpm-version: 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm ${{ matrix.node-pnpm-combo.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.node-pnpm-combo.pnpm-version }}

      - name: Set up Node.js ${{ matrix.node-pnpm-combo.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-pnpm-combo.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
